; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; !!! This file must be UTF-8 with BOM !!!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TODO: Update the version numbers
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

#define MyAppName        "RisohEditor"
#define MyAppVersion     GetStringFileInfo('build\Release\RisohEditor64.exe',"FileVersion")
#define MyAppCompanyName "Katayama Hirofumi MZ"
#define CurrentYear      GetDateTimeString('yyyy','','')
#define MyAppCopyright   "(c) 2017-" + CurrentYear + " " + MyAppCompanyName
#define MyAppURL         "http://katahiromz.web.fc2.com/"
#define MyAppDescription "RisohEditor 64-bit"

#include                 "installer_languages.iss"

AppId={{AF7494D1-4064-4D04-A8FE-8F9DAB97F664}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion} 64-bit

VersionInfoCompany={#MyAppCompanyName}
VersionInfoCopyright={#MyAppCopyright}
VersionInfoDescription={#MyAppDescription} installer
VersionInfoProductName={#MyAppName} 64-bit
VersionInfoProductTextVersion={#MyAppVersion}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoVersion={#MyAppVersion}

UninstallDisplayIcon={app}\{#MyAppName}64.exe
AppPublisher={#MyAppCompanyName}

AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

ShowLanguageDialog=yes
UsePreviousLanguage=no
LanguageDetectionMethod=uilanguage

DefaultDirName={pf64}\{#MyAppName}64
DefaultGroupName={#MyAppName} 64-bit
DisableDirPage=no
AllowNoIcons=yes
LicenseFile=LICENSE.rtf
OutputDir=.
OutputBaseFilename={#MyAppName}-{#MyAppVersion}-x64-setup
SetupIconFile=src\res\Icon_100.ico
Compression=lzma
SolidCompression=yes
UsePreviousAppDir=yes

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "rc_association"; Description: "{cm:AssociateRcFiles}"
Name: "res_association"; Description: "{cm:AssociateResFiles}"

[Files]
Source: "README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_es.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_id.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_it.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_ja.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_ko.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_pt_BR.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_ru.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_tr.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "README_uk.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_es.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_id.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_it.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_ja.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_ko.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_pt_BR.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "ChangeLog_uk.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "Standardize.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "HYOJUNKA.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "TRANSLATORS.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "mcdx\MESSAGETABLEDX.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "build\Release\RisohEditor64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "src\resource.h"; DestDir: "{app}"; Flags: ignoreversion
Source: "data\Constants.txt"; DestDir: "{app}\data"; Flags: ignoreversion
Source: "build\Release\mcdx.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "src\MOleHost.hpp"; DestDir: "{app}\OLE"; Flags: ignoreversion
Source: "src\MOleHost.cpp"; DestDir: "{app}\OLE"; Flags: ignoreversion
Source: "src\MWindowBase.hpp"; DestDir: "{app}\OLE"; Flags: ignoreversion
Source: "src\DlgInit.h"; DestDir: "{app}\DlgInit"; Flags: ignoreversion
Source: "src\Toolbar.h"; DestDir: "{app}\Toolbar"; Flags: ignoreversion
Source: "MyWndCtrl\MWindowBase.hpp"; DestDir: "{app}\MyWndCtrl"; Flags: ignoreversion
Source: "MyWndCtrl\MyWndCtrl.cpp"; DestDir: "{app}\MyWndCtrl"; Flags: ignoreversion
Source: "MyWndCtrl\CMakeLists.txt"; DestDir: "{app}\MyWndCtrl"; Flags: ignoreversion
Source: "build\Release\MyWndCtrl.dll"; DestDir: "{app}\MyWndCtrl"; Flags: ignoreversion
Source: "data\bin\libgcc_s_dw2-1.dll"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\libwinpthread-1.dll"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\windres.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\upx.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\mcpp.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\dfmsc.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\olebow.exe"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "data\bin\midlwrap.bat"; DestDir: "{app}\data\bin"; Flags: ignoreversion
Source: "EGA\EGA-Manual.pdf"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA\samples\fact.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA\samples\break.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\Censorship.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\DeleteNonEnglish.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\NeutralToEnglish.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_clone_by_lang.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_delete.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_select.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_set_binary.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_set_text.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_str_get.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "EGA-samples\RES_str_set.ega"; DestDir: "{app}\EGA"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\commctrl.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\dlgs.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\richedit.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\windef.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\windows.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\winnt.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\winresrc.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\winuser.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\winver.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "data\lib\gcc\i686-w64-mingw32\10.2.0\include\afxres.h"; DestDir: "{app}\data\lib\gcc\i686-w64-mingw32\10.2.0\include"; Flags: ignoreversion
Source: "win32-samples\DialogBox\.gitignore"; DestDir: "{app}\win32-samples\DialogBox"; Flags: ignoreversion
Source: "win32-samples\DialogBox\CMakeLists.txt"; DestDir: "{app}\win32-samples\DialogBox"; Flags: ignoreversion
Source: "win32-samples\DialogBox\DialogBox.cpp"; DestDir: "{app}\win32-samples\DialogBox"; Flags: ignoreversion
Source: "win32-samples\DialogBox\DialogBox_res.rc"; DestDir: "{app}\win32-samples\DialogBox"; Flags: ignoreversion
Source: "win32-samples\DialogBox\resource.h"; DestDir: "{app}\win32-samples\DialogBox"; Flags: ignoreversion
Source: "win32-samples\DialogBox\lang\en_US.rc"; DestDir: "{app}\win32-samples\DialogBox\lang"; Flags: ignoreversion
Source: "win32-samples\MainWnd\.gitignore"; DestDir: "{app}\win32-samples\MainWnd"; Flags: ignoreversion
Source: "win32-samples\MainWnd\CMakeLists.txt"; DestDir: "{app}\win32-samples\MainWnd"; Flags: ignoreversion
Source: "win32-samples\MainWnd\MainWnd.cpp"; DestDir: "{app}\win32-samples\MainWnd"; Flags: ignoreversion
Source: "win32-samples\MainWnd\MainWnd_res.rc"; DestDir: "{app}\win32-samples\MainWnd"; Flags: ignoreversion
Source: "win32-samples\MainWnd\resource.h"; DestDir: "{app}\win32-samples\MainWnd"; Flags: ignoreversion
Source: "win32-samples\MainWnd\lang\en_US.rc"; DestDir: "{app}\win32-samples\MainWnd\lang"; Flags: ignoreversion
Source: "win32-samples\MainWnd\res\Icon_100.ico"; DestDir: "{app}\win32-samples\MainWnd\res"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\CMakeLists.txt"; DestDir: "{app}\win32-samples\ToolbarTest"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\ToolbarTest.cpp"; DestDir: "{app}\win32-samples\ToolbarTest"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\ToolbarTest_res.rc"; DestDir: "{app}\win32-samples\ToolbarTest"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\lang\en_US.rc"; DestDir: "{app}\win32-samples\ToolbarTest\lang"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\res\Bitmap_100.bmp"; DestDir: "{app}\win32-samples\ToolbarTest\res"; Flags: ignoreversion
Source: "win32-samples\ToolbarTest\resource.h"; DestDir: "{app}\win32-samples\ToolbarTest"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\RisohEditor 64-bit"; Filename: "{app}\RisohEditor64.exe"
Name: "{group}\{cm:ReadmeEnglish}"; Filename: "{app}\README.txt"
Name: "{group}\{cm:ReadmeJapanese}"; Filename: "{app}\README_ja.txt"
Name: "{group}\{cm:LicenseEnglish}"; Filename: "{app}\LICENSE.txt"
Name: "{group}\{cm:ProgramOnTheWeb,RisohEditor}"; Filename: "http://katahiromz.web.fc2.com"
Name: "{group}\{cm:UninstallProgram,RisohEditor}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\RisohEditor 64-bit"; Filename: "{app}\RisohEditor64.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\RisohEditor64.exe"; Description: "{cm:LaunchProgram,RisohEditor}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKCU; Subkey: "Software\Katayama Hirofumi MZ\RisohEditor64"; Flags: deletekey uninsdeletekey
; .rc
Root: HKCR; Subkey: ".rc"; ValueType: string; ValueName: ""; ValueData: "RisohEditor.ResourceFile"; Flags: uninsdeletevalue; Tasks: "rc_association"
Root: HKCR; Subkey: "RisohEditor.ResourceFile"; ValueType: string; ValueName: ""; ValueData: "RisohEditor Resource File"; Flags: uninsdeletekey; Tasks: "rc_association"
Root: HKCR; Subkey: "RisohEditor.ResourceFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\RisohEditor64.exe,0"; Tasks: "rc_association"
Root: HKCR; Subkey: "RisohEditor.ResourceFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\RisohEditor64.exe"" ""%1"""; Tasks: "rc_association"
; .res
Root: HKCR; Subkey: ".res"; ValueType: string; ValueName: ""; ValueData: "RisohEditor.BinaryResourceFile"; Flags: uninsdeletevalue; Tasks: "res_association"
Root: HKCR; Subkey: "RisohEditor.BinaryResourceFile"; ValueType: string; ValueName: ""; ValueData: "RisohEditor Binary Resource File"; Flags: uninsdeletekey; Tasks: "res_association"
Root: HKCR; Subkey: "RisohEditor.BinaryResourceFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\RisohEditor64.exe,0"; Tasks: "res_association"
Root: HKCR; Subkey: "RisohEditor.BinaryResourceFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\RisohEditor64.exe"" ""%1"""; Tasks: "res_association"
