#ifndef RESOURCE_H_
#define RESOURCE_H_

#define ID_NEW              100
#define ID_OPEN             101
#define ID_SAVEAS           102
#define ID_EXIT             103
#define ID_ADDICON          104
#define ID_ADDCURSOR        105
#define ID_ADDBITMAP        106
#define ID_ADDRES           108
#define ID_REPLACEICON      109
#define ID_REPLACECURSOR    110
#define ID_REPLACEBITMAP    111
#define ID_REPLACEBIN       112
#define ID_DELETERES        113
#define ID_EDIT             114
#define ID_EXTRACTICON      115
#define ID_EXTRACTCURSOR    116
#define ID_EXTRACTBITMAP    117
#define ID_EXTRACTBIN       118
#define ID_ABOUT            119
#define ID_TEST             120
#define ID_IMPORT           121
#define ID_COMPILE          122
#define ID_CANCELEDIT       123
#define ID_SHOWDIALOG       124
#define ID_GUIEDIT          125
#define ID_ADDCTRL          126
#define ID_DELCTRL          127
#define ID_CTRLPROP         128
#define ID_DLGPROP          129
#define ID_DESTROYRAD       130
#define ID_UPDATERES        131
#define ID_CTRLINDEXTOP     132
#define ID_CTRLINDEXBOTTOM  133
#define ID_CTRLINDEXMINUS   134
#define ID_CTRLINDEXPLUS    135
#define ID_SHOWHIDEINDEX    136
#define ID_TOPALIGN         137
#define ID_BOTTOMALIGN      138
#define ID_LEFTALIGN        139
#define ID_RIGHTALIGN       140
#define ID_TEXTEDIT         141

#define IDD_REPLACERES      100
#define IDD_ADDICON         101
#define IDD_REPLACEICON     102
#define IDD_ADDBITMAP       103
#define IDD_REPLACEBMP      104
#define IDD_ADDRES          105
#define IDD_ADDCURSOR       106
#define IDD_REPLACECUR      107
#define IDD_MENUTEST        108
#define IDD_ADDKEY          109
#define IDD_MODIFYKEY       110
#define IDD_EDITACCEL       111
#define IDD_ADDSTR          112
#define IDD_MODIFYSTR       113
#define IDD_STRINGS         114
#define IDD_ADDMITEM        115
#define IDD_MODIFYMITEM     116
#define IDD_EDITMENU        117
#define IDD_DLGPROP         118
#define IDD_CTRLPROP        119
#define IDD_ADDCTRL         120

#define IDS_APPNAME         1
#define IDS_TITLEWITHFILE   2
#define IDS_EXTRACTRES      3
#define IDS_RESBINFILTER    4
#define IDS_CANNOTSAVE      5
#define IDS_REPLACERES      6
#define IDS_ALLFILES        7
#define IDS_ENTERTYPE       8
#define IDS_ENTERNAME       9
#define IDS_ENTERLANG       10
#define IDS_FILENOTFOUND    11
#define IDS_CANNOTREPLACE   12
#define IDS_EXEFILTER       13
#define IDS_SAVEAS          14
#define IDS_CANNOTADDICON   15
#define IDS_ADDICON         16
#define IDS_ICOFILTER       17
#define IDS_REPLACEICO      18
#define IDS_CANTREPLACEICO  19
#define IDS_EXISTSOVERWRITE 20
#define IDS_OPEN            21
#define IDS_CANNOTOPEN      22
#define IDS_ADDBMP          23
#define IDS_BMPFILTER       24
#define IDS_CANTREPLACEBMP  25
#define IDS_REPLACEBMP      26
#define IDS_ERRORCODE       27
#define IDS_VERSIONINFO     28
#define IDS_ADDRES          29
#define IDS_CANNOTADDRES    30
#define IDS_CANTADDBMP      31
#define IDS_EXTRACTBMP      32
#define IDS_CANTEXTRACTBMP  33
#define IDS_CANTREPLACECUR  34
#define IDS_CANNOTADDCUR    35
#define IDS_CURFILTER       36
#define IDS_ADDCUR          37
#define IDS_REPLACECUR      38
#define IDS_EXTRACTICO      39
#define IDS_CANTEXTRACTICO  40
#define IDS_EXTRACTCUR      41
#define IDS_CANTEXTRACTCUR  42
#define IDS_RESFILTER       43
#define IDS_NEUTRAL         44
#define IDS_IMPORTRES       45
#define IDS_CANNOTIMPORT    46
#define IDS_COMPILE         47
#define IDS_CANCELEDIT      48
#define IDS_GUIEDIT         49
#define IDS_CANNOTSTARTUP   51
#define IDS_RESMISMATCH     52
#define IDS_SAMPLETEXT      53
#define IDS_ALREADYEXISTS   54
#define IDS_KEY             55
#define IDS_FLAGS           56
#define IDS_COMMANDID       57
#define IDS_INVALIDKEY      58
#define IDS_COMPILEERROR    59
#define IDS_STRINGID        60
#define IDS_STRINGVALUE     61
#define IDS_CAPTION         62
#define IDS_HELPID          63
#define IDS_INDENT          64
#define IDS_DATAISEMPTY     65
#define IDS_TEST            66
#define IDS_SEPARATOR       67
#define IDS_COMPILENOW      68
#define IDS_RADWINDOW       69
#define IDS_ENTERCLASS      70
#define IDS_TEXTEDIT        71

#endif  // ndef RESOURCE_H_
